quadruped_robot_project:
# Publish all joint states -----------------------------------
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

# Position Controllers ---------------------------------------
    right_front_elbow_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: right_front_elbow_joint
        pid: {p: 5000.0, i: 100.0, d: 0.0}
    right_front_wrist_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: right_front_wrist_joint
        pid: {p: 5000.0, i: 100.0, d: 0.0}




    right_back_elbow_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: right_back_elbow_joint
        pid: {p: 5000.0, i: 100.0, d: 0.0}
    right_back_wrist_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: right_back_wrist_joint
        pid: {p: 5000.0, i: 100.0, d: 0.0}




    left_back_elbow_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: left_back_elbow_joint
        pid: {p: 5000.0, i: 100.0, d: 0.0}
    left_back_wrist_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: left_back_wrist_joint
        pid: {p: 5000.0, i: 100.0, d: 0.0}




    left_front_elbow_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: left_front_elbow_joint
        pid: {p: 5000.0, i: 100.0, d: 0.0}
    left_front_wrist_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: left_front_wrist_joint
        pid: {p: 5000.0, i: 100.0, d: 0.0}

